nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.4.cjs

npmAuthToken: "$NPM_AUTH_TOKEN"

npmPublishRegistry: https://registry.npmjs.org/
npmRegistryServer: https://registry.npmjs.org/
npmPublishAccess: public
npmRegistries:
  "//registry.npmjs.org":
    "npmAuthToken": $NPM_AUTH_TOKEN