endpoint: wss://polkadot-asset-hub-rpc.polkadot.io
mock-signature-host: true
port: 8002
block: 17481668
db: ./db-assethub.sqlite

import-storage:
  System:
    Account:
      - [[14Md8aehwVoc1kFWfBHfjqTjMAH91R3TpZkEKvmV893fSfQ8], { providers: 1, data: { free: '10000000000000000000' } }]
  Assets:
    Account:
      - [[1984, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
      - [[1337, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
      - [[21, 5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY], { balance: 1000000000 }]
    Asset: [[[21], { supply: 1000000000 }]]

