endpoint: wss://rpc2-paseo.xcavate.io
mock-signature-host: true
block: ${env.FREQUENCY_BLOCK_NUMBER}
db: ./db.sqlite
runtime-log-level: 5

import-storage:
  System:
    Account:
      -
        -
          - 5DHdfcUJ1ms94Qn3F5RED4YKKHa2ewJpMTNr1J6JZzk4Xrpn
        - providers: 1
          data:
            free: 1000000000000000
